version: '3'

services:
  front:
    image: ${IMAGE_NAME}
    network_mode: "host"
    environment:
        - PORT=${FRONTED_PORT}

  media:
    image: ${IMAGE_NAME}
    network_mode: "host"
    environment:
      - PORT=${MEDIA_PORT}

  compose:
    image: ${IMAGE_NAME}
    network_mode: "host"
    environment:
      - PORT=${COMPOSE_POST_PORT}

  user:
    image: ${IMAGE_NAME}
    network_mode: "host"
    environment:
      - PORT=${USER_PORT}

  text:
    image:  ${IMAGE_NAME}
    network_mode: "host"
    environment:
      - PORT=${TEXT_PORT}

  url_shorten:
    image:  ${IMAGE_NAME}
    network_mode: "host"
    environment:
      - PORT=${URL_SHORTEN_PORT}

  user_mention:
    image:  ${IMAGE_NAME}
    network_mode: "host"
    environment:
      - PORT=${USER_MENTION_PORT}

  user_timeline:
    image:  ${IMAGE_NAME}
    network_mode: "host"
    environment:
      - PORT=${USER_TIMELINE_PORT}

  post_storage:
    image:  ${IMAGE_NAME}
    network_mode: "host"
    environment:
      - PORT=${POST_STORAGE_PORT}

  upload_text:
    image:  ${IMAGE_NAME}
    network_mode: "host"
    environment:
      - PORT=${UPLOAD_TEXT_PORT}

  unique_id:
    image:  ${IMAGE_NAME}
    network_mode: "host"
    environment:
      - PORT=${UNIQUE_ID_PORT}

